---
title: "Sign-Up for Nuclear Fantasy Football Leagues"
subtitle: "Enrolling in a league managed by Nuclear Fantasy Football"
tagline: "How Do I Sign-Up for a NuclearFF League?"
author: "Nolan MacDonald"
created: "2025-09-24"
updated: "2025-09-24"
category: "general"
author_avatar: "logos/nuclearff-logo.png"
output: html_fragment
---

# NuclearFF Leagues

Sign-ups for Nuclear Fantasy Football leagues are posted during the off-season.
If a league spot has opened up in an existing league or if we are planning to open 
a new league, announcements are posted in all leagues and social media.

Keep an eye on the league chat if you are already in a NuclearFF league or join the discord for off-season announcements on league openings, signing-up for new leagues, and the addition of alternative formats. 

<blockquote>
NuclearFF league sign-ups occur in the off-season for open spots and new leagues.
We continue to expand the number of formats and leagues year-over-year.
Check the Discord or your league chat if you are already in a NuclearFF league for sign-up information.
</blockquote>

## What Formats Do You Offer?

NuclearFF leagues include redraft, dynasty, survivor, and chopped formats for the 2025 season. In 2024, NuclearFF also included a vampire format.
Each season, we continue to evolve by adding additional fantasy football formats we think others would be interested in.
Suggestions for new leagues or reviving old formats are always welcome by posting in the Discord.