---
title: "Dynasty Leagues Taxi Squads Explained"
subtitle: "Understanding the role of taxi squads in dynasty leagues"
tagline: "What is a Taxi Squad?"
author: "Nolan MacDonald"
created: "2025-09-23"
updated: "2025-09-23"
category: "waivers"
author_avatar: "logos/nuclearff-logo.png"
output: html_fragment
---

# Taxi Squads

Taxi squads are available in dynasty fantasy football leagues that allow 
teams to stash extra players that are either rookies or early in their career.
Taxi squad players do not count against the active roster limit.

<blockquote>
Taxi squads provide teams with additional roster flexibility to develop 
young players.
</blockquote>

# Taxi Squad Slots

Taxi squads are limited to a certain amount of players defined by the league
commissioner.
The league commissioner can allow anywhere from 0 to 10 players on a taxi squad,
depending on the league.
To add a player to a slot in a team's taxi squad, the team must first add the
player as a free agent or waiver wire pickup first to the starting lineup or
bench.
Teams can then move the player to the taxi squad, freeing up a roster spot.
There is no current capabilities to add a player directly to the taxi squad.
Taxi slots are eligible to rookies and players between 1-4 years of experience,
depending on the league settings.

# Forming a Taxi Squad

A team may assemble a taxi squad by adding eligible players to taxi slots if
the player's experience is less than the taxi squad duration defined in the
league settings.
Taxi squad players can only be moved to an open slot once the player is on a
team's starting lineup or bench.
Non-rookies are allowed on taxi depending on a league's settings.

## Years of Eligibility

Taxi slots and eligibility are defined in the league settings as taxi squad
duration.
The taxi squad duration is the amount of years of experience a player has.
For example, if the taxi squad duration is set to 2 years, this means that
players with 0, 1, or 2 years of experience are eligible to be placed on the
taxi squad. The year of experience is determined at the end of each NFL season.

<blockquote>
Players are eligible for taxi based on league settings for taxi squad duration.
This is the number of years of experience a player has, updated at the end of
each NFL season.
</blockquote>

## Taxi Squad Deadline

Taxi squads have a deadline for when players can be moved to the taxi squad
prior to the taxi squad slots being locked.
Typically, a taxi squad deadline is set to the start of the NFL regular season,
requiring all players to be moved to open slots prior to the start of Week 1.

## Can I Move Players In and Out of a Taxi Squad?

Players can be moved in and out of taxi squads with a few notes.
Teams can move taxi squad players to the starting lineup or bench at any time.

<blockquote>
Teams can **always** move players from the taxi squad to the starting lineup 
or bench.
Teams have a deadline for moving players into taxi slots.
</blockquote>

Teams can **only** move players into taxi slots prior to the taxi squad deadline.
Once the taxi squad deadline has passed, players can no longer be moved to
taxi slots.
