---
title: "Injured Reserve (IR) and Player Injury Status"
subtitle: "Rosters injured reserve and options for eligible players"
tagline: "How Do Injury Status Designations and IR Work?"
author: "Nolan MacDonald"
created: "2025-09-24"
updated: "2025-09-24"
category: "rosters"
author_avatar: "logos/nuclearff-logo.png"
output: html_fragment
---

# Injured Reserve (IR)

Injured Reserve (IR) are additional slots on team rosters specifically for
players that are unable to play.
Depending on the IR settings the league commissioner has set, teams
may have the option to place players on IR, if injured reserve slots is not
set to zero.

<blockquote>
Players eligible for IR by default include those with the player status
designation <span style="color:red; font-weight:bold;">PUP</span> or <span style="color:red; font-weight:bold;">IR</span>.
</blockquote>

Additional options for IR eligibility include players who will not play for
a designated week (OUT), players who are doubtful or unlikely to
play (DOUB), suspended players (SUS), players who did not
report or are on holdout (DNR), and players with COVID-19.

# Injury Status Designation 

A player's injury tag can change multiple times throughout the week in the
regular season.
If a player is ruled out for a specific week, the injury status designation
applies to that week only. 
This means that a player ruled out will not retain the out status beyond that
specific week, reset on Wednesdays.

<blockquote>
Players cannot retain the <span style="color:red; font-weight:bold;">OUT</span>
status unless they have been officially ruled out for their next game.
</blockquote>

An overview of player injury designations are listed below.

- **PROBABLE**: Player is likely to play
- **QUESTIONABLE**: Player has a 50/50 shot to play, could have limited reps
- **DOUBTFUL**: Player is not likely to play
- **OUT**: Player will not play for designated week
- **SUSPENDED**: Player is suspended and will not play
- **IR**: Player has been placed on injured reserve and will not play (minimum 4 weeks)
- **PUP**: Player has been placed on Physically Unable to Perform (PUP) list and will not play (minimum 4 weeks)

## Bye Weeks

Bye weeks operate differently for a player's injury status.
On a player's bye week, they will retain their injury status from the previous
week.
For example, if a player on a roster is ruled out in Week 13, and the
player's team is on bye in Week 14, they will keep the out status for both
weeks.
This also applies to players designated with suspended, questionable, doubtful, and COVID-19. 

## Locked Rosters

If a player is no longer eligible for IR, a team must create roster space
to move the player back to the bench or starting lineup.
Teams cannot make any additional roster edits, add players from free agency,
or add players from the waiver wire until this is resolved.

If a team does not have roster space and prefers to not drop a player,
the additional option is to explore trading a player from the roster to create
space.



