---
title: "Fantasy League Trade Deadlines" 
subtitle: "Figuring out the last possible moment to make trades"
tagline: "How Do Trade Deadlines Work?"
author: "NuclearFF Team"
created: "2024-02-05"
updated: "2024-11-28"
category: "trading"
author_avatar: "logos/nuclearff-logo.png"
output: html_fragment
---

# Overview

The trade deadline is the final period of the fantasy football regular season
where teams can make trades for draft picks, FAAB, or players.
Trade deadlines are set to prevent teams from making trades that could unfairly benefit competing teams in the playoffs.
The deadline is set to prevent collusion and prevent situations where teams that will not make the playoffs from trading away key players for lesser value.
League trade deadlines can vary by league based on the commissioner settings.

# Sleeper Trade Deadlines

The trade deadline set in a Sleeper league allows teams to accept trades 
up until the end of the specified week.
Trades can be accepted until the final game of the week has ended.
If a league has a set time to review pending trades, the trade can be processed
after the deadline.

<blockquote>
The trade deadline occurs in leagues at the conclusion of the final game for the specified NFL week.
</blockquote>

Sleeper fantasy football trade deadlines are set by the league commissioner.
By default, Sleeper trade deadlines are set to Week 11 of the NFL season.
Some leagues may vary to allow additional time for trading, 
such as the Week 12 deadline set for the NUCLEARFF REDRAFT league.
It is common that most leagues are set to Week 11, 
allowing enough time to configure your roster before the start of fantasy 
playoffs that typically begin in Week 14 or 15.

# Trade Deadline Example

For example, if a league has defined a trade deadline of Week 11 on Sleeper,
this means that all trades must be accepted before the final game Week 11 ends.
Trades can no longer be accepted once the final game of Week 11 has 
ended on Monday night.
In this case, this means that you can propose and accept trades up until
the end of Week 11.
In 2024, the Week 11 trade deadline was Monday, November 18th at the conclusion
of the matchup between the Houston Texans and Dallas Cowboys.
Week 11 trade deadlines in 2025 occur at the end of the Dallas Cowboys 
and Las Vegas Raiders matchup on Monday, November 17th.

# When is Trading Allowed Again?

Redraft leagues do not allow trading after the deadline, and trading will
be enabled again when the next season is renewed prior to the fantasy draft.

Dynasty and keeper leagues differ, as these formats allow trading as soon
as the league has been renewed for the new season after the playoffs have concluded.
