---
title: "Trading Draft Picks" 
subtitle: "Draft pick trades before drafts, during drafts, and in-season"
tagline: "Is Draft Pick Trading Allowed?"
author: "Nolan MacDonald"
created: "2025-09-24"
updated: "2025-09-24"
category: "trading"
author_avatar: "logos/nuclearff-logo.png"
output: html_fragment
---

# Trading Draft Picks

Trading draft picks can be important for a team to acquire the necessary
picks they desire to go and get their guys or acquire more draft capital.
Draft pick trading is permitted across all league formats, including redraft, keeper, dynasty, and chopped leagues.

<blockquote>
Draft pick trading is allowed for all leagues types.
This includes redraft, keeper, dynasty, and chopped leagues.
</blockquote>

*Note that for a redraft league, draft pick trading is only allowed prior to
the draft starting.*
If the option for draft pick trading does not appear to be available,
request the commissioner to enable the setting "Allow Draft Pick Trading" in 
a Sleeper league's settings.
To keep track of draft pick trades, refer to the Sleeper draftboard, which reflects all picks that were traded. The draftboard visually displays which team the draft pick was traded to.

Keep in mind that teams are allowed to draft over the roster limits in leagues where players are retained season-to-season like dynasty and keeper leagues.
This means that if you have more picks than available slots on your roster,
this can be addressed after the draft when a team has made all their picks.
During the draft, all rosters are locked, meaning that teams cannot add or drop players.

# Trading During Live Drafts

Draft pick trading is allowed during live drafts, except for redraft leagues.
Each time a draft pick is traded, the league's draftboard will update to show
the newly acquired picks for teams.

## Trading for the Pick on the Clock

If a team trades for the draft pick that is currently on the clock, the pick timer
**WILL NOT RESET**. 
For example, assume a team trades for pick 1.5 in a draft that has a 5 minute pick timer. If there is 2 minutes and 30 seconds remaining on the clock when they acquire the pick, they will only have 2 minutes and 30 seconds to make that pick.
