---
title: "Waiver Wire Formats"
subtitle: "Different waiver wire types and what they mean"
tagline: "What are the Different Types of Waivers?"
author: "Nolan MacDonald"
created: "2025-09-23"
updated: "2025-09-23"
category: "waivers"
author_avatar: "logos/nuclearff-logo.png"
output: html_fragment
---

# Waiver Wire Formats

The waiver wire, or waivers, is where unclaimed players are put on a temporary
hold before teams have an opportunity to add them to a their roster via a claim.
Depending on the format, when waivers are processed, the team with the highest
waiver priority will be awarded the player.
The league commissioner defines the waiver format or type in the league 
settings.
Waiver types include rolling waivers, reverse standings, and FAAB bidding.

<blockquote>
There are three main types of waiver wire formats: rolling waivers, reverse
standings, and FAAB bidding.
Each format has its own advantages and disadvantages.
</blockquote>

The waiver wire will work differently depending on a league's settings defined
by the commissioner.
The three different types of waivers are described below.

## Rolling Waivers

Rolling waivers is the default format on the Sleeper platform.
When a league uses rolling waivers, the waiver priority is continuous,
based on the last team to waiver a player being moved to the end of the queue.
For every waiver claim that is successful, the team is moved to the end of the
queue that adds the player off waivers, and the remaining teams are moved up.

<blockquote>
Rolling waivers is a continuous waiver format where the team that last
successfully claimed a player is moved to the end of the queue.
</blockquote

## Reverse Standings

Rather than continuous waivers, reverse standings waivers reset each week
based on the standings. 
The teams with the worst records have the highest priority (e.g., The team in
last place has the highest priority).
The reverse standings waiver format allows for prioritizing teams that need 
roster development to improve their team.

<blockquote>
Reverse standings waivers prioritize teams with the worst records to help
improve their roster.
</blockquote>

## FAAB Bidding

FAAB, or Free Agent Acquisition Budget, is an alternative to traditional 
waivers.
Each team is provided with a budget (e.g., $100) to acquire players through
waivers using a blind bidding process.

<blockquote>
FAAB bidding allows teams to acquire players through
waivers using a blind bidding process. This gives everyone an opportunity to 
acquire the players they prefer, rather than relying on waiver priority.
</blockquote>

When waivers are processed, the team with the highest bid is awarded the player.
Bids can be defined by the commissioner with a required minimum bid, which
is set to $0 by default.